openapi: '3.0.0'
info:
  title: Train Booking
  version: '1.0'
  description: train Booking systeam 
servers:
  - url: http://localhost:4000

tags:
  - name: stations
    description: Everything about stations

paths:
  /api/stations/get-stations:
    get:
      tags:
        - "stations"
      summary: "Return all stations"
      description: 'return all stations'
      responses:
        '200':
          $ref: '#/components/responses/allStations'
        '400':
          $ref: '#/components/responses/errorRes'

components:
  responses:
    allStations:
      description: 'OK'
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: status of response.
              data:
                type: array
                description: payload of response.
                items:
                  type: object
                  properties:
                      id:
                        type: integer
                      station_name:
                        type: string
                      created_at:
                        type: string
                      updated_at:
                        type: string
    errorRes:
      description: 'Error'
      content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                  default: false
                  description: status of response.
                status:
                  type: integer
                  default: 400
                  description: status code of response.
                data:
                  type: object
                  description: message error
                  properties:
                    message:
                       type: string